# Generated by Django 3.2.3 on 2021-05-23 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('prereq', models.CharField(max_length=50)),
                ('dep', models.CharField(max_length=50)),
                ('available', models.BooleanField()),
            ],
        ),
    ]
